apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocdlab-app
  namespace: argocdlab
  labels:
    app: argocdlab-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocdlab-app
  template:
    metadata:
      labels:
        app: argocdlab-app
    spec:
      containers:
        - name: argocdlab-app
          image: wericknalyson/argocdlab-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: APP_VERSION
              value: "1.0.0"
            - name: PORT
              value: "3000"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
