apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocdlab-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Replace YOUR_GITHUB_USERNAME with your GitHub username
    repoURL: https://github.com/werick-nalyson/simple-argocd-lab.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: argocdlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
